spring.application.name=Hospital
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/hospital_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:WJ28@krhps}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true